# All possible characters to be used in names (including uppercase)
valid-name-characters: "abcdefghijklmnopqrstuvwxyz1234567890.-_ "

# Maximum length for names
max-name-length: 16

# Maximum length for prefixes
max-prefix-length: 8

# Maximum length for suffixes
max-suffix-length: 8

# Whether colors are enabled or not
enable-colors: true

# Game masters
game-masters: