name: PlayerNameTags
version: '0.0.6-custom'
main: me.gonkas.playernametags.PlayerNameTags
api-version: '1.21'
authors: [Gonkas77]
commands:
  name:
    description: "Creates a ghost entity following the player with a custom name to replace the player's name tag."
    permission: playernametags.change_names
  removename:
    description: "Removes any existing custom name tags from a certain player."
    permission: playernametags.remove_names
  lockchat:
    description: "Prevents non-operators or non-'game-masters' (see config) from chatting or seeing player chat messages."
    permission: playernametags.lock_chat
  unlockchat:
    description: "Prevents non-operators or non-'game-masters' (see config) from chatting or seeing player chat messages."
    permission: playernametags.unlock_chat
  gamemaster:
    description: "???"
    permission: playernametags.admin